### ISSUE TITLE
Commit some code.

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Tamagotchi-2.0#19]
It is Feb 2 and no actual code has been committed this year. This is Not Good.

**Comment by Briggsdf** [comment]
Prof.Vidal,
I am not in your CSCE 492 class. I believe I'm still attached to the group.

**Comment by josemvidal** [comment]
Ask the team to take you off. In fact, they should be seeing this message
already.

On Sun, Feb 2, 2014 at 5:55 PM, Briggsdf notifications@github.com wrote:

> Prof.Vidal,
> I am not in your CSCE 492 class. I believe I'm still attached to the group.
> On Feb 2, 2014 5:51 PM, "Jose M Vidal" notifications@github.com wrote:
> 
> > It is Feb 2 and no actual code has been committed this year. This is Not
> > Good.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/SCCapstone/Tamagotchi-2.0/issues/19>
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/SCCapstone/Tamagotchi-2.0/issues/19#issuecomment-33916081
> .

## 

Jose M Vidal, Undergraduate Director, Computer Science and Engineering
http://jmvidal.cse.sc.edu

**Comment by josemvidal** [comment]
Even better, add an issue: "take me off this group".

On Sun, Feb 2, 2014 at 5:56 PM, Jose M Vidal jmvidal@gmail.com wrote:

> Ask the team to take you off. In fact, they should be seeing this message
> already.
> 
> On Sun, Feb 2, 2014 at 5:55 PM, Briggsdf notifications@github.com wrote:
> 
> > Prof.Vidal,
> > I am not in your CSCE 492 class. I believe I'm still attached to the
> > group.
> > On Feb 2, 2014 5:51 PM, "Jose M Vidal" notifications@github.com wrote:
> > 
> > > It is Feb 2 and no actual code has been committed this year. This is Not
> > > Good.
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/SCCapstone/Tamagotchi-2.0/issues/19>
> > > .
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/SCCapstone/Tamagotchi-2.0/issues/19#issuecomment-33916081
> > .
> 
> ## 
> 
> Jose M Vidal, Undergraduate Director, Computer Science and Engineering
> http://jmvidal.cse.sc.edu

## 

Jose M Vidal, Undergraduate Director, Computer Science and Engineering
http://jmvidal.cse.sc.edu
