### ISSUE TITLE
Did Not give your app to the other team.

### ISSUE THREAD

**Issue by josemvidal** [SCCapstone/Tamagotchi-2.0#27]
What's up. You are going to lose the game in the last quarter.

In case the sports metaphor was not clear, your grade has suffered a Lot since you abandoned this project.

**Comment by evan-robbins** [comment]
There was some confusion about which group we were evaluating and which group was evaluating us.  After reviewing the list of RC1 testing assignments, I sent an email to all of the members of SSChildcare using Blackboard.

**Comment by josemvidal** [comment]
Please keep this issue open until you actually add bugs reports to their Issues.
